#!/bin/sh
#
# urandom	This script saves the random seed between reboots.
#		It is called from the boot, halt and reboot scripts.
#
# Version:	@(#)urandom  1.33  22-Jun-1998  miquels@cistron.nl
#

LIGHTBLUE="\e[38;5;87m"
LIGHTGREEN="\e[38;5;46m"
LIGHTRED="\e[38;5;196m"
NORMAL="\e[0m"
OK="${LIGHTGREEN}OK${NORMAL}"
FAIL="${LIGHTRED}FAIL${NORMAL}"
HEADER="${LIGHTBLUE}[S20 urandom]${NORMAL}\t"

[ -c /dev/urandom ] || exit 0
#. /etc/default/rcS

case "$1" in
	start|"")
		echo -ne "${HEADER}Starting initializing random number generator..."  > /dev/kmsg

		# Load and then save 512 bytes,
		# which is the size of the entropy pool

		dmesg | sha512sum > /dev/urandom
		[ $? = 0 ] && echo -e "${HEADER}started ${OK}" || echo -e "${HEADER}start ${FAIL}" > /dev/kmsg
		;;
	stop)
		;;
	*)
		echo "Usage: urandom {start|stop}" >&2
		exit 1
		;;
esac
