#!/bin/sh

LIGHTBLUE="\e[38;5;87m"
LIGHTGREEN="\e[38;5;46m"
LIGHTRED="\e[38;5;196m"
NORMAL="\e[0m"
OK="${LIGHTGREEN}OK${NORMAL}"
FAIL="${LIGHTRED}FAIL${NORMAL}"
HEADER="${LIGHTBLUE}[S21 misc]${NORMAL}\t"

xo_correction() {

	XO_ENV_VAL=`fw_printenv -n xo_correction 2> /dev/null`
	if [ $? -eq 0 ]; then

		for dev in /sys/bus/iio/devices/*; do
			[ `cat ${dev}/name` == "ad9361-phy" ] && DEV_NAME=`basename ${dev}`
		done

		echo ${XO_ENV_VAL} > /sys/bus/iio/devices/${DEV_NAME}/xo_correction
	fi
}


case "$1" in
	start|"")
		echo -ne "${HEADER}Starting miscellaneous setup..." > /dev/kmsg
		xo_correction
		MAX_BS=`fw_printenv -n iio_max_block_size 2> /dev/null || echo 67108864`
		echo ${MAX_BS} > /sys/module/industrialio_buffer_dma/parameters/max_block_size
		[ $? = 0 ] && echo -e "${HEADER}${OK}" > /dev/kmsg || echo -e "${HEADER}${FAIL}" > /dev/kmsg
		;;
	stop)

		;;
	*)
		echo "Usage: $0 {start|stop}" >&2
		exit 1
		;;
esac
