#!/bin/sh
# Server-side demuxing by default

LIGHTBLUE="\e[38;5;87m"
LIGHTGREEN="\e[38;5;46m"
LIGHTRED="\e[38;5;196m"
NORMAL="\e[0m"
OK="${LIGHTGREEN}OK${NORMAL}"
FAIL="${LIGHTRED}FAIL${NORMAL}"
HEADER="${LIGHTBLUE}[S45 msd]${NORMAL}\t"

source /etc/device_config

CONF=/opt/config.txt
file=/sys/kernel/config/usb_gadget/composite_gadget/functions/mass_storage.0/lun.0/file
img=/tmp/vfat.img

patch_html_page() {
	LINUX=`uname -a | tr / - | tr '\n' ';' ; echo -n $(nproc) "core(s)"`
	MODEL=`cat /etc/libiio.ini | grep hw_model= | cut -d '=' -f 2`
	SERIAL=`cat /sys/kernel/config/usb_gadget/composite_gadget/strings/0x409/serialnumber`
	MACHOST=`cat /sys/kernel/config/usb_gadget/composite_gadget/functions/rndis.0/host_addr`
	MAC=`cat /sys/kernel/config/usb_gadget/composite_gadget/functions/rndis.0/dev_addr`
	IIO=`iio_info 2>/dev/null | grep "Library version:"`
	BUILD=`grep device-fw /opt/VERSIONS | cut -d ' ' -f 2`
	FPGA=`grep hdl /opt/VERSIONS | cut -d ' ' -f 2`
	ROOTFS=`grep buildroot /opt/VERSIONS | cut -d ' ' -f 2`
	UBOOT=`cat /proc/cmdline | tr  "=" "\n" | grep "U-Boot"`

	sed -i -e "s/#LINUX#/$LINUX/g" -e "s/#MODEL#/$MODEL/g" -e "s/#SERIAL#/$SERIAL/g" -e "s/#MACHOST#/$MACHOST/g" -e "s/#MAC#/$MAC/g" -e "s/#IIO#/$IIO/g" -e "s/#BUILD#/$BUILD/g" -e "s/#FPGA#/$FPGA/g" -e "s/#ROOTFS#/$ROOTFS/g" -e "s/#UBOOT#/$UBOOT/g" $1

	sed -i -e "s/#BUILD#/$BUILD/g" $2 /etc/motd
}


case "$1" in
	start)
		echo -ne "${HEADER}Starting MSD Daemon..." > /dev/kmsg
		patch_html_page "/www/index.html /www/img/index_*.html" /www/img/version.js
        dd if=/dev/zero of=$img bs=1M seek=30 count=0
        mkfs.vfat -n PlutoSDR $img
		mount $img /mnt

		if [ "$TARGET" == "m2k" ]; then
			cp /opt/${CALIBFILENAME} /mnt
			md5sum /mnt/${CALIBFILENAME} > /opt/${CALIBFILENAME}.md5
		fi

		cp $CONF /mnt
		md5sum /mnt/config.txt > /opt/config.md5

		cp -a /www/* /mnt/
		mv /mnt/index.html /mnt/info.html
		sed -i -e "s/..\/index.html/..\/info.html/g" /mnt/img/index_*.html
		umount /mnt
		echo $img > $file

		start-stop-daemon -S -b -q -m -p /var/run/update.pid -x /bin/sh -- /sbin/update.sh
		[ $? = 0 ] && echo -e "${HEADER}started ${OK}" || echo -e "${HEADER}start ${FAIL}" > /dev/kmsg
		;;

	stop)
		echo -ne "${HEADER}Stopping MSD Daemon..." > /dev/kmsg
		start-stop-daemon -K -q -p /var/run/update.pid 2>/dev/null
		[ $? = 0 ] && echo -e "${HEADER}stopped ${OK}" || echo -e "${HEADER}stop ${FAIL}" > /dev/kmsg
		;;

	restart)
		$0 stop
		sleep 1
		$0 start
		;;

	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac
