#!/bin/sh

case "$1" in
	start)
		mount /dev/mtdblock4 /mnt
        mkdir -p /mnt/.work /mnt/upper /overlay
        mount -t overlay overlay -olowerdir=/,upperdir=/mnt/upper,workdir=/mnt/.work /overlay
        mount --bind /dev /overlay/dev
        mount --bind /proc /overlay/proc
        mount --bind /dev/pts /overlay/dev/pts
        mount --bind /dev/shm /overlay/dev/shm
        mount --bind /tmp /overlay/tmp
        mount --bind /run /overlay/run
        mount --bind /sys /overlay/sys
        mount --bind /sys/kernel/debug /overlay/sys/kernel/debug
        mount --bind /sys/kernel/config /overlay/sys/kernel/config
        mount --bind /dev/iio_ffs /overlay/dev/iio_ffs
		;;

	stop)
		umount /overlay/dev/iio_ffs
        umount /overlay/sys/kernel/config
        umount /overlay/sys/kernel/debug
        umount /overlay/sys
        umount /overlay/run
        umount /overlay/tmp
        umount /overlay/dev/shm
        umount /overlay/dev/pts
        umount /overlay/proc
        umount /overlay/dev
        umount /overlay
        umount /dev/mtdblock4
		;;

	restart)
		$0 stop
		$0 start
		;;

	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac
