#!/bin/sh

case "$1" in
	start)
        mkdir -p /overlay /overlay/mnt /overlay/merged
        mount /dev/mtdblock4 /overlay/mnt
        mkdir -p /overlay/mnt/work /overlay/mnt/upper
        mount -t overlay overlay -olowerdir=/,upperdir=/overlay/mnt/upper,workdir=/overlay/mnt/work /overlay/merged
        mount --bind /dev /overlay/merged/dev
        mount --bind /proc /overlay/merged/proc
        mount --bind /dev/pts /overlay/merged/dev/pts
        mount --bind /dev/shm /overlay/merged/dev/shm
        mount --bind /tmp /overlay/merged/tmp
        mount --bind /run /overlay/merged/run
        mount --bind /sys /overlay/merged/sys
        mount --bind /sys/kernel/debug /overlay/merged/sys/kernel/debug
        mount --bind /sys/kernel/config /overlay/merged/sys/kernel/config
        mount --bind /dev/iio_ffs /overlay/merged/dev/iio_ffs
		;;

	stop)
		umount /overlay/merged/dev/iio_ffs
        umount /overlay/merged/sys/kernel/config
        umount /overlay/merged/sys/kernel/debug
        umount /overlay/merged/sys
        umount /overlay/merged/run
        umount /overlay/merged/tmp
        umount /overlay/merged/dev/shm
        umount /overlay/merged/dev/pts
        umount /overlay/merged/proc
        umount /overlay/merged/dev
        umount /overlay/merged
        umount /overlay/mnt
		;;

	restart)
		$0 stop
		$0 start
		;;

	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac
