
LIBRARY_NAME := e31x_core

LIBRARY_SRC += $(ETTUS_FPGA_DIR)/usrp3/top/e31x/e31x_core.v
LIBRARY_SRC += $(ETTUS_FPGA_DIR)/usrp3/top/e31x/e31x_rfnoc_image_core.v
LIBRARY_SRC += $(ETTUS_FPGA_DIR)/usrp3/top/e31x/ip/fifo_4k_2clk/fifo_4k_2clk.xci
LIBRARY_SRC += $(ETTUS_FPGA_DIR)/usrp3/top/e31x/ip/fifo_short_2clk/fifo_short_2clk.xci
LIBRARY_SRC += $(ETTUS_FPGA_DIR)/usrp3/lib/axi/axis_data_swap.v
LIBRARY_SRC += $(ETTUS_FPGA_DIR)/usrp3/lib/axi/axis_downsizer.v
LIBRARY_SRC += $(ETTUS_FPGA_DIR)/usrp3/lib/axi/axis_packet_flush.v
LIBRARY_SRC += $(ETTUS_FPGA_DIR)/usrp3/lib/axi/axis_upsizer.v
LIBRARY_SRC += $(ETTUS_FPGA_DIR)/usrp3/lib/axi/axis_width_conv.v
LIBRARY_SRC += $(ETTUS_FPGA_DIR)/usrp3/lib/control/axil_regport_master.v
LIBRARY_SRC += $(ETTUS_FPGA_DIR)/usrp3/lib/control/axi_setting_reg.v
LIBRARY_SRC += $(ETTUS_FPGA_DIR)/usrp3/lib/control/db_control.v
LIBRARY_SRC += $(ETTUS_FPGA_DIR)/usrp3/lib/control/gpio_atr.v
LIBRARY_SRC += $(ETTUS_FPGA_DIR)/usrp3/lib/control/pulse_stretch_min.v
LIBRARY_SRC += $(ETTUS_FPGA_DIR)/usrp3/lib/control/pulse_synchronizer.v
LIBRARY_SRC += $(ETTUS_FPGA_DIR)/usrp3/lib/control/ram_2port.v
LIBRARY_SRC += $(ETTUS_FPGA_DIR)/usrp3/lib/control/regport_resp_mux.v
LIBRARY_SRC += $(ETTUS_FPGA_DIR)/usrp3/lib/control/reset_sync.v
LIBRARY_SRC += $(ETTUS_FPGA_DIR)/usrp3/lib/control/setting_reg.v
LIBRARY_SRC += $(ETTUS_FPGA_DIR)/usrp3/lib/control/simple_spi_core.v
LIBRARY_SRC += $(ETTUS_FPGA_DIR)/usrp3/lib/control/synchronizer.v
LIBRARY_SRC += $(ETTUS_FPGA_DIR)/usrp3/lib/control/synchronizer_impl.v
LIBRARY_SRC += $(ETTUS_FPGA_DIR)/usrp3/lib/control/map/axis_muxed_kv_map.v
LIBRARY_SRC += $(ETTUS_FPGA_DIR)/usrp3/lib/control/map/cam.v
LIBRARY_SRC += $(ETTUS_FPGA_DIR)/usrp3/lib/control/map/cam_bram.v
LIBRARY_SRC += $(ETTUS_FPGA_DIR)/usrp3/lib/control/map/cam_priority_encoder.v
LIBRARY_SRC += $(ETTUS_FPGA_DIR)/usrp3/lib/control/map/cam_srl.v
LIBRARY_SRC += $(ETTUS_FPGA_DIR)/usrp3/lib/control/map/kv_map.v
LIBRARY_SRC += $(ETTUS_FPGA_DIR)/usrp3/lib/fifo/axi_demux.v
LIBRARY_SRC += $(ETTUS_FPGA_DIR)/usrp3/lib/fifo/axi_fifo.v
LIBRARY_SRC += $(ETTUS_FPGA_DIR)/usrp3/lib/fifo/axi_fifo_2clk.v
LIBRARY_SRC += $(ETTUS_FPGA_DIR)/usrp3/lib/fifo/axi_fifo_bram.v
LIBRARY_SRC += $(ETTUS_FPGA_DIR)/usrp3/lib/fifo/axi_fifo_flop.v
LIBRARY_SRC += $(ETTUS_FPGA_DIR)/usrp3/lib/fifo/axi_fifo_flop2.v
LIBRARY_SRC += $(ETTUS_FPGA_DIR)/usrp3/lib/fifo/axi_fifo_short.v
LIBRARY_SRC += $(ETTUS_FPGA_DIR)/usrp3/lib/fifo/axi_mux.v
LIBRARY_SRC += $(ETTUS_FPGA_DIR)/usrp3/lib/fifo/axi_packet_gate.v
LIBRARY_SRC += $(ETTUS_FPGA_DIR)/usrp3/lib/fifo/axis_fifo_monitor.v
LIBRARY_SRC += $(ETTUS_FPGA_DIR)/usrp3/lib/fifo/axis_strm_monitor.v
LIBRARY_SRC += $(ETTUS_FPGA_DIR)/usrp3/lib/rfnoc/blocks/rfnoc_block_radio/noc_shell_radio.v
LIBRARY_SRC += $(ETTUS_FPGA_DIR)/usrp3/lib/rfnoc/blocks/rfnoc_block_radio/radio_core.v
LIBRARY_SRC += $(ETTUS_FPGA_DIR)/usrp3/lib/rfnoc/blocks/rfnoc_block_radio/radio_rx_core.v
LIBRARY_SRC += $(ETTUS_FPGA_DIR)/usrp3/lib/rfnoc/blocks/rfnoc_block_radio/radio_tx_core.v
LIBRARY_SRC += $(ETTUS_FPGA_DIR)/usrp3/lib/rfnoc/blocks/rfnoc_block_radio/rfnoc_block_radio.v
LIBRARY_SRC += $(ETTUS_FPGA_DIR)/usrp3/lib/rfnoc/core/axis_ctrl_master.v
LIBRARY_SRC += $(ETTUS_FPGA_DIR)/usrp3/lib/rfnoc/core/axis_ctrl_slave.v
LIBRARY_SRC += $(ETTUS_FPGA_DIR)/usrp3/lib/rfnoc/core/backend_iface.v
LIBRARY_SRC += $(ETTUS_FPGA_DIR)/usrp3/lib/rfnoc/core/axis_data_to_chdr.v
LIBRARY_SRC += $(ETTUS_FPGA_DIR)/usrp3/lib/rfnoc/core/chdr_compute_tkeep.v
LIBRARY_SRC += $(ETTUS_FPGA_DIR)/usrp3/lib/rfnoc/core/chdr_data_swapper.v
LIBRARY_SRC += $(ETTUS_FPGA_DIR)/usrp3/lib/rfnoc/core/chdr_ingress_fifo.v
LIBRARY_SRC += $(ETTUS_FPGA_DIR)/usrp3/lib/rfnoc/core/chdr_mgmt_pkt_handler.v
LIBRARY_SRC += $(ETTUS_FPGA_DIR)/usrp3/lib/rfnoc/core/chdr_stream_endpoint.v
LIBRARY_SRC += $(ETTUS_FPGA_DIR)/usrp3/lib/rfnoc/core/chdr_stream_input.v
LIBRARY_SRC += $(ETTUS_FPGA_DIR)/usrp3/lib/rfnoc/core/chdr_stream_output.v
LIBRARY_SRC += $(ETTUS_FPGA_DIR)/usrp3/lib/rfnoc/core/chdr_to_axis_ctrl.v
LIBRARY_SRC += $(ETTUS_FPGA_DIR)/usrp3/lib/rfnoc/core/chdr_to_axis_data.v
LIBRARY_SRC += $(ETTUS_FPGA_DIR)/usrp3/lib/rfnoc/core/ctrlport_endpoint.v
LIBRARY_SRC += $(ETTUS_FPGA_DIR)/usrp3/lib/rfnoc/core/rfnoc_core_kernel.v
LIBRARY_SRC += $(ETTUS_FPGA_DIR)/usrp3/lib/rfnoc/crossbar/axis_ctrl_crossbar_2d_mesh.v
LIBRARY_SRC += $(ETTUS_FPGA_DIR)/usrp3/lib/rfnoc/crossbar/axis_ctrl_crossbar_nxn.v
LIBRARY_SRC += $(ETTUS_FPGA_DIR)/usrp3/lib/rfnoc/crossbar/axis_ingress_vc_buff.v
LIBRARY_SRC += $(ETTUS_FPGA_DIR)/usrp3/lib/rfnoc/crossbar/axis_port_terminator.v
LIBRARY_SRC += $(ETTUS_FPGA_DIR)/usrp3/lib/rfnoc/crossbar/axis_switch.v
LIBRARY_SRC += $(ETTUS_FPGA_DIR)/usrp3/lib/rfnoc/crossbar/chdr_xb_ingress_buff.v
LIBRARY_SRC += $(ETTUS_FPGA_DIR)/usrp3/lib/rfnoc/crossbar/chdr_xb_routing_table.v
LIBRARY_SRC += $(ETTUS_FPGA_DIR)/usrp3/lib/rfnoc/crossbar/chdr_crossbar_nxn.v
LIBRARY_SRC += $(ETTUS_FPGA_DIR)/usrp3/lib/rfnoc/crossbar/mesh_2d_dor_router_single_sw.v
LIBRARY_SRC += $(ETTUS_FPGA_DIR)/usrp3/lib/rfnoc/crossbar/torus_2d_dor_router_single_sw.v
LIBRARY_SRC += $(ETTUS_FPGA_DIR)/usrp3/lib/rfnoc/utils/ctrlport_clk_cross.v
LIBRARY_SRC += $(ETTUS_FPGA_DIR)/usrp3/lib/rfnoc/utils/ctrlport_combiner.v
LIBRARY_SRC += $(ETTUS_FPGA_DIR)/usrp3/lib/rfnoc/utils/ctrlport_decoder.v
LIBRARY_SRC += $(ETTUS_FPGA_DIR)/usrp3/lib/rfnoc/utils/ctrlport_decoder_param.v
LIBRARY_SRC += $(ETTUS_FPGA_DIR)/usrp3/lib/rfnoc/utils/ctrlport_splitter.v
LIBRARY_SRC += $(ETTUS_FPGA_DIR)/usrp3/lib/rfnoc/utils/ctrlport_to_settings_bus.v
LIBRARY_SRC += $(ETTUS_FPGA_DIR)/usrp3/lib/rfnoc/utils/timekeeper.v
LIBRARY_SRC += $(ETTUS_FPGA_DIR)/usrp3/lib/rfnoc/xport/chdr_xport_adapter_generic.v
LIBRARY_SRC += $(ETTUS_FPGA_DIR)/usrp3/lib/rfnoc/xport/liberio_chdr64_adapter.v

TOOLS_DIR = $(ETTUS_FPGA_DIR)/usrp3/tools
GIT_HASH = $(shell $(TOOLS_DIR)/scripts/git-hash.sh --hashfile=$(TOOLS_DIR)/../../project.githash)
GIT_HASH_VERILOG_DEF = $(addprefix GIT_HASH=32'h,$(GIT_HASH))
EDGE_FILE = $(abspath $(ETTUS_FPGA_DIR)/usrp3/top/e31x/e310_static_router.hex)
EDGE_TBL_DEF = "RFNOC_EDGE_TBL_FILE=$(EDGE_FILE)"
VERILOG_DEFS = $(GIT_HASH_VERILOG_DEF) $(EDGE_TBL_DEF)
$(info $(VERILOG_DEFS))

GENERIC_DEPS += $(LIBRARY_SRC)
XILINX_DEPS += $(LIBRARY_NAME)_ip.tcl
export
include library/scripts/library.mk


