#!/bin/sh

case "$1" in
	start)
		start-stop-daemon -S -b -q -m -p /var/run/zmq_routing.pid -x /usr/bin/tx2_zmq_routing.py
		[ $? = 0 ] && echo "OK" || echo "FAIL"
		;;

	stop)
		start-stop-daemon -K -q -p /var/run/zmq_routing.pid 2>/dev/null
		[ $? = 0 ] && echo "OK" || echo "FAIL"
		;;

	restart)
		$0 stop
		sleep 1
		$0 start
		;;

	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac
