
LIBRARY_NAME := e310_io

GENERIC_DEPS += ../ettus-fpga/usrp3/top/e31x/e310_io.v
GENERIC_DEPS += ../ettus-fpga/usrp3/lib/control/synchronizer.v
GENERIC_DEPS += ../ettus-fpga/usrp3/lib/control/synchronizer_impl.v

XILINX_DEPS += $(LIBRARY_NAME)_ip.tcl

include library/scripts/library.mk
