#!/bin/sh

# devtmpfs does not get automounted for initramfs
/bin/mount -t devtmpfs devtmpfs /dev

/bin/mkdir -p /overlay /overlay/mnt /overlay/merged
if ! /bin/mount -t jffs2 /dev/mtdblock4 /overlay/mnt; then
    flash_erase /dev/mtd4
    /bin/mount -t jffs2 /dev/mtdblock4 /overlay/mnt
fi

exec 0</dev/console
exec 1>/dev/console
exec 2>/dev/console

/bin/mkdir -p /overlay/mnt/work /overlay/mnt/upper
if /bin/mount -t overlay overlay -olowerdir=/,upperdir=/overlay/mnt/upper,workdir=/overlay/mnt/work /overlay/merged; then
    /bin/mount --bind /dev /overlay/merged/dev
    exec chroot /overlay/merged /sbin/init "$@"
else
    exec /sbin/init "$@"
fi
