
LIBRARY_NAME := axi_gpreg

GENERIC_DEPS += library/common/ad_rst.v
GENERIC_DEPS += library/common/up_axi.v
GENERIC_DEPS += library/common/up_clock_mon.v
GENERIC_DEPS += axi_gpreg.v
GENERIC_DEPS += axi_gpreg_clock_mon.v
GENERIC_DEPS += axi_gpreg_io.v

XILINX_DEPS += library/xilinx/common/ad_rst_constr.xdc
XILINX_DEPS += axi_gpreg_ip.tcl

include library/scripts/library.mk
